config/routes.rb
Lunchy::Application.routes.draw do
  
  resources :locations
  resources :users
  
  get "pages/home"
  get "pages/contact"

  
  match "/", :to => "home#index", :via => "get"
  match '/signup',  :to => 'users#create'
  match "/", :to => "users#login", :via => "post"
  match "/locations", :to => "locations#create", :via => "post"
  match "/locations/edit", :to => "locations#edit", :via => "get"
  match "/restaurants", :to => "restaurants#index", :via => "get"
  match "/restaurants", :to => "restaurants#search", :via => "post"
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :restaurants
  has_and_belongs_to_many :users
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @user = User.find(session[:user_id])
    @locations = @user.locations

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    
    
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    city,state = params[:location]["city"].split(",")
    @location = Location.new(:city => city, :state => state)
    user = User.find(session[:user_id])
    user.locations << @location
    user.save
    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/edit.html.erb
<div id="map_canvas" class="map rounded">
	
	<p>Hello World! <p>
</div>


<div id="map_canvas" class="map rounded">
	
	<p>Hello World! <p>
</div>
<div id="map_canvas" class="map rounded">
	
	<p>Hello World! <p>
</div>

<div id="map_canvas" class="map rounded">
	
	<p>Hello World! <p>
</div>
<div id="map_canvas" class="map rounded">
	
	<p>Hello World! <p>
</div>
<div id="map_canvas" class="map rounded">
	
	<p>Hello World! <p>
</div>
<div id="map_canvas" class="map rounded">
	
	<p>Hello World! <p>
</div>

app/views/locations/index.html.erb
<h1 class="normal"> Welcome <%= @user.name %>!</h1>

<div class="well add_location">
  <h2 class="normal"> Add a location</h2>
  	<%= form_for("location", :html => { :class => "search-query"}) do |f| %> 
	    <%= f.text_field(:city,:class => "search-query", :placeholder => "City, State") %>
		<%= f.submit('Add', :class => "btn")%>
    <% end %>
</div>

<div class="well current_locations">
  <h2 class="normal"> Your current locations</h2>
  <% @user.locations.each do |location| %>
    <%= link_to location.city, :controller => "restaurants", :action => "index", :location_id => location.id %>
  <% end %>
</div>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= link_to 'Back', locations_path %>